### ISSUE TITLE
Creación del componente api-virtual-assistant-core

### ISSUE THREAD

**Issue by DanielNicolasCarvajalOrtega** [nicolasOrtega23/virtual-assistant#1]
Requerimientos funcionales:

Se debe crear para el comienzo de la api de chatbot virtual assistant un componente llamado api-virtual-assinstant-core con un enpoint que permita saludar a los usuarios que interactuén con el.

El endpoint debe tener esta nomesclatura
GET {context-path}/v1/virtual-assistant-core/welcome

Este GET debe devolver un status 200 con el texto de saludo en formato json para que los sistemas que se integren  puedan leerlo
de esta forma:

{
     welcome: "Welcome to virtual assistant.. how do you to do today?"
}

- Para darle termino al endpoint se deben hacer las pruebas unitarias y de integración necesarias para asegurar la calidad del código ademas de adjuntar el postman para futuras pruebas.
-

**Comment by nicolasOrtega23** [comment]
![metodos http](https://github.com/user-attachments/assets/1ce69133-d908-4487-b89b-ef95f74197cd)

**Comment by nicolasOrtega23** [comment]
GET y RETURN.

from flask import Flask

app = Flask(__name__)

@app.route("/holaMundo/") # --> GET
def hello_world():
    return ("<h1 style = color:red> Hello </h1>"  # --> RETURN
            "<h2 style = color:blue> World! </h2>")

@app.route("/holaMundo/saludo")  # --> GET
def saludo():
    return "<p style = color:red>Te saludamos!</p>"  # --> RETURN


if __name__ == "__main__":
    app.run()

**Comment by nicolasOrtega23** [comment]
RETURN DEL GET.

![hello_world](https://github.com/user-attachments/assets/04c24b0d-19fb-4ba1-bc85-5786429f9c74)
![saludo](https://github.com/user-attachments/assets/5ed3465f-01f3-47a9-b805-09fc07356f1a)

**Comment by DanielNicolasCarvajalOrtega** [comment]
@jdanieldeveloper , me puedes revisar este commit porfavor.
